.ORIG X3000
main:

	; Registers backup
	ST R0, R0_SAVE_MAIN
	ST R1, R1_SAVE_MAIN
	ST R2, R2_SAVE_MAIN
	ST R3, R3_SAVE_MAIN
	ST R4, R4_SAVE_MAIN
	ST R5, R5_SAVE_MAIN
	ST R6, R6_SAVE_MAIN
	ST R7, R7_SAVE_MAIN

	LD R5 GETNUM_ADDRESS
	JSRR R5 ; Get the first number and put it in R0_TEMP
	ADD R0 R2 #0

	JSRR R5 ; Get the second number and out it in R1
	ADD R1 R2 #0

	LD R5 CALCULATOR_ADDRESS
	JSRR R5

	; Putting previous values
	LD R0, R0_SAVE_MAIN
	LD R1, R1_SAVE_MAIN
	LD R2, R2_SAVE_MAIN
	LD R3, R3_SAVE_MAIN
	LD R4, R4_SAVE_MAIN
	LD R5, R5_SAVE_MAIN
	LD R6, R6_SAVE_MAIN
	LD R7, R7_SAVE_MAIN

	HALT

	R0_SAVE_MAIN .FILL #0
	R1_SAVE_MAIN .FILL #0
	R2_SAVE_MAIN .FILL #0
	R3_SAVE_MAIN .FILL #0
	R4_SAVE_MAIN .FILL #0
	R5_SAVE_MAIN .FILL #0
	R6_SAVE_MAIN .FILL #0
	R7_SAVE_MAIN .FILL #0

	GETNUM_ADDRESS .FILL x41F4
	CALCULATOR_ADDRESS .FILL x4384

.END
